Repository surfstudio/ReactiveDataDisplayManager, pull requests merged in 2021-12, with the labels that each got.

#148 Idpt 737 RDDM. Плагин фокусировки для tvOs
  .swiftpm/xcode/package.xcworkspace/contents.xcworkspacedata
  Example/ReactiveDataDisplayManagerExample.xcodeproj/project.pbxproj
  Example/ReactiveDataDisplayManagerExampleTv/Collection/CollectionDefaultBehavoirController.swift
  Example/ReactiveDataDisplayManagerExampleTv/Collection/GalleryController.swift
  Example/ReactiveDataDisplayManagerExampleTv/Extensions/UIImage.swift
  Example/ReactiveDataDisplayManagerExampleTv/Main.storyboard
  Example/ReactiveDataDisplayManagerExampleTv/Main/MainTableController.swift
  Example/ReactiveDataDisplayManagerExampleTv/Table/TableController.swift
  Example/ReactiveDataDisplayManagerExampleTv/Views/Cells/ImageCollectionViewCell/ImageCollectionViewCell.swift
  Example/ReactiveDataDisplayManagerExampleTv/Views/Cells/ImageCollectionViewCell/ImageCollectionViewGenerator.swift
  Example/ReactiveDataDisplayManagerExampleTv/Views/Cells/ImageDefaultBehavoirCell/ImageDefaultBehavoirCollectionViewCell.swift
  Example/ReactiveDataDisplayManagerExampleTv/Views/Cells/ImageDefaultBehavoirCell/ImageDefaultBehavoirCollectionViewCell.xib
  Example/ReactiveDataDisplayManagerExampleTv/Views/Cells/ImageDefaultBehavoirCell/ImageDefaultBehavoirCollectionViewGenerator.swift
  Example/ReactiveDataDisplayManagerExampleTv/Views/Cells/ImageViewModel.swift
  Example/ReactiveDataDisplayManagerExampleTv/Views/Cells/TitleTableViewCell/TitleTableViewCell.swift
  Example/ReactiveDataDisplayManagerExampleTv/Views/Cells/TitleTableViewCell/TitleTableViewCell.xib
  Example/ReactiveDataDisplayManagerExampleTv/Views/Cells/TitleTableViewCell/TitleTableViewCellModel.swift
  Example/ReactiveDataDisplayManagerExampleTv/Views/Cells/TitleTableViewCell/TitleTableViewGenerator.swift
  ReactiveDataDisplayManager.xcodeproj/project.pbxproj
  Source/Collection/CollectionBuilder.swift
  Source/Collection/Delegate/BaseCollectionDelegate.swift
  Source/Models/FocusedPlaginModels/FocusableAlign.swift
  Source/Models/FocusedPlaginModels/FocusablePluginBorderModel.swift
  Source/Models/FocusedPlaginModels/FocusedPluginShadowModel.swift
  Source/Models/FocusedPlaginModels/FocusedPluginTransformModel.swift
  Source/Protocols/Plugins/FeaturePlugin/FocusablePlugin/Focusable.swift
  Source/Protocols/Plugins/FeaturePlugin/FocusablePlugin/FocusablePlugin.swift
  Source/Protocols/Plugins/FeaturePlugin/FocusablePlugin/FocusablePluginDelegate.swift
  Source/Protocols/Plugins/FeaturePlugin/FocusablePlugin/FocusableStrategy/FocusableStrategy.swift
  Source/Protocols/Plugins/FeaturePlugin/FocusablePlugin/FocusableStrategy/Strategy/BorderFocusableStrategy.swift
  Source/Protocols/Plugins/FeaturePlugin/FocusablePlugin/FocusableStrategy/Strategy/CompositFocusableTableStrategy.swift
  Source/Protocols/Plugins/FeaturePlugin/FocusablePlugin/FocusableStrategy/Strategy/ScrollFocusableCollectionItem.swift
  Source/Protocols/Plugins/FeaturePlugin/FocusablePlugin/FocusableStrategy/Strategy/ScrollFocusableTableCell.swift
  Source/Protocols/Plugins/FeaturePlugin/FocusablePlugin/FocusableStrategy/Strategy/ShadowFocusableStrategy.swift
  Source/Protocols/Plugins/FeaturePlugin/FocusablePlugin/FocusableStrategy/Strategy/TransformFocusableStrategy.swift
  Source/Protocols/Plugins/Generators/FocusableItem.swift
  Source/Table/Delegate/BaseTableDelegate.swift
  Source/Table/TableBuilder.swift
Labels: feature

#150 IDPT-820 DragAndDpoppable. Не правильный индекс при вставке
  Example/ReactiveDataDisplayManagerExample.xcodeproj/project.pbxproj
  Source/Protocols/Plugins/FeaturePlugin/DragAndDroppablePlugin/DroppablePluginDelegate.swift
Labels: Blocker

#152 IDPT-823 RDDM. Невозможно переопределить isNeedDeselect у генератора
  Example/ReactiveDataDisplayManager/Table.storyboard
  Example/ReactiveDataDisplayManager/Table/MainTableViewController/MainTableViewController.swift
  Example/ReactiveDataDisplayManager/Table/SelectableTableViewController/SelectableTableViewController.swift
  Example/ReactiveDataDisplayManagerExample.xcodeproj/project.pbxproj
  Source/Collection/Generators/BaseCollectionCellGenerator.swift
  Source/Collection/Plugins/PluginAction/CollectionSelectablePlugin.swift
  Source/Protocols/Plugins/Generators/SelectableItem.swift
  Source/Table/Generators/BaseCellGenerator.swift
  Source/Table/Generators/BaseNonReusableCellGenerator.swift
  Source/Table/Generators/CalculatableHeightNonReusableCellGenerator.swift
  Source/Table/Plugins/PluginAction/TableSelectablePlugin.swift
Labels: feature

#154 Idpt 821 make entry for baseNonReusable
  Example/ReactiveDataDisplayManager/Collection/DynamicHeightViewController/DynamicHeightViewController.swift
  Example/ReactiveDataDisplayManager/Collection/Views/Cells/DynamicHeightViewCell/DynamicHeightTableViewCell.swift
  Example/ReactiveDataDisplayManagerExample.xcodeproj/project.pbxproj
  ReactiveDataDisplayManager.xcodeproj/project.pbxproj
  SPMExample/ReactiveDataDisplayManagerSPMExample/ExamplePackage/Sources/ExamplePackage/Table/MainSPMTableViewController.swift
  SPMExample/ReactiveDataDisplayManagerSPMExample/ExamplePackage/Sources/ExamplePackage/Table/Views/Cells/SPMTableViewCell/SPMTableViewCell.swift
  Source/Models/ConstructionType.swift
  Source/Protocols/Plugins/Generators/ConstructableItem.swift
  Source/Table/Generators/BaseNonReusableCellGenerator.swift
  Source/Table/TableCell+RDDM.swift
Labels: ToDo, Normal
