Repository surfstudio/ReactiveDataDisplayManager, pull requests merged in 2021-04, with the labels that each got.

#124 Feature/IDPT-706/Example for Compositional Layout
  Example/ReactiveDataDisplayManager/Base.lproj/Main.storyboard
  Example/ReactiveDataDisplayManager/Collection/CollectionCompositionalViewController/CollectionCompositionalViewController.swift
  Example/ReactiveDataDisplayManager/Collection/CollectionListViewController/CollectionListViewController.swift
  Example/ReactiveDataDisplayManager/Collection/MainCollectionViewController/MainCollectionViewController.swift
  Example/ReactiveDataDisplayManager/Utils/NukeImagePrefetcher.swift
  Example/ReactiveDataDisplayManagerExample.xcodeproj/project.pbxproj
Labels: feature

#126 Feature/IDPT-725/CollectionFooter
  Example/ReactiveDataDisplayManager/Collection/CollectionCompositionalViewController/CollectionCompositionalViewController.swift
  Example/ReactiveDataDisplayManager/Collection/Views/Footer/TitleIconCollectionFooterGenerator.swift
  Example/ReactiveDataDisplayManager/Collection/Views/Footer/TitleIconCollectionFooterView.swift
  Example/ReactiveDataDisplayManager/Collection/Views/Footer/TitleIconCollectionFooterView.xib
  Example/ReactiveDataDisplayManagerExample.xcodeproj/project.pbxproj
  ReactiveDataDisplayManager.xcodeproj/project.pbxproj
  ReactiveDataDisplayManagerTests/BaseCollectionDataDisplayManagerTests.swift
  Source/Collection/DataSource/BaseCollectionDataSource.swift
  Source/Collection/DataSource/CollectionGeneratorsProvider.swift
  Source/Collection/Delegate/FlowCollectionDelegate.swift
  Source/Collection/Deprecated/BaseCollectionDataDisplayManager.swift
  Source/Collection/Generators/EmptyCollectionFooterGenarator.swift
  Source/Collection/Manager/BaseCollectionManager.swift
  Source/Protocols/FooterDataDisplayManager.swift
  Source/Protocols/Protocols.swift
Labels: feature

#127 update roadmap
  Documentation/Roadmap/ROADMAP.csv
  Documentation/Roadmap/ROADMAP.itmz
  Documentation/Roadmap/ROADMAP.md
  Documentation/Roadmap/ROADMAP.png
Labels: feature

#114 Feature/idpt 616/diffable table datasource
  Example/ReactiveDataDisplayManager/Collection/CollectionListViewController/CollectionListViewController.swift
  Example/ReactiveDataDisplayManager/Collection/ImageHorizontalCollectionViewController/ImageHorizontalCollectionViewController.swift
  Example/ReactiveDataDisplayManager/Collection/MainCollectionViewController/MainCollectionViewController.swift
  Example/ReactiveDataDisplayManager/Extensions/UIViewController.swift
  Example/ReactiveDataDisplayManager/Main.storyboard
  Example/ReactiveDataDisplayManager/Table/DiffableTableViewController/DiffableTableViewController.swift
  Example/ReactiveDataDisplayManager/Table/MainTableViewController/MainTableViewController.swift
  Example/ReactiveDataDisplayManager/Table/Views/Cells/Generators/DiffableCellGenerator.swift
  Example/ReactiveDataDisplayManager/Table/Views/Headers/Generators/TitleHeaderGenerator.swift
  Example/ReactiveDataDisplayManagerExample.xcodeproj/project.pbxproj
  Example/Tricolor/Application/Info/Debug/Info.plist
  ReactiveDataDisplayManager.xcodeproj/project.pbxproj
  Source/Collection/Animator/CollectionBatchUpdatesAnimator.swift
  Source/Collection/Deprecated/BaseCollectionDataDisplayManager.swift
  Source/Collection/Manager/BaseCollectionManager.swift
  Source/Collection/Plugins/PluginAction/BaseCollectionPlugin.swift
  Source/Protocols/Animator/Animator.swift
  Source/Protocols/Modifier/Modifier.swift
  Source/Protocols/Plugins/Generators/DiffableItem.swift
  Source/Protocols/Protocols.swift
  Source/Table/Animator/TableBatchUpdatesAnimator.swift
  Source/Table/Animator/TableUpdatesAnimator.swift
  Source/Table/DataSource/BaseTableDataSource.swift
  Source/Table/DataSource/DiffableTableDataSource.swift
  Source/Table/DataSource/TableDataSource.swift
  Source/Table/Delegate/BaseTableDelegate.swift
  Source/Table/Delegate/TableDelegate.swift
  Source/Table/Deprecated/BaseTableDataDisplayManager.swift
  Source/Table/Deprecated/GravityTableDataDisplayManager.swift
  Source/Table/Generators/EmptyHeaderGenerator.swift
  Source/Table/Manager/BaseTableManager.swift
  Source/Table/Manager/GravityTableManager.swift
  Source/Table/Manager/ManualTableManager.swift
  Source/Table/Modifier/TableCommonModifier.swift
  Source/Table/Modifier/TableDiffableModifier.swift
  Source/Table/Plugins/PluginAction/BaseTablePlugin.swift
  Source/Table/Plugins/PluginAction/TablePrefetcherablePlugin.swift
  Source/Table/Table+RDDM.swift
  Source/Table/TableBuilder.swift
  Source/Table/TableBuilderConfigurable.swift
  Source/Utils/AnyEquatable.swift
  Tricolor/Application/Info/Debug/Info.plist
Labels: Refactoring, feature

#117 Feature/idpt 691/documentation in code
  Example/ReactiveDataDisplayManager/Application/AppDelegate.swift
  Example/ReactiveDataDisplayManager/Collection/FoldableCollectionViewController/FoldableCollectionViewController.swift
  Example/ReactiveDataDisplayManager/Collection/SizableCollectionViewController/SizableCollectionViewController.swift
  Example/ReactiveDataDisplayManagerExample.xcodeproj/project.pbxproj
  ReactiveDataDisplayManager.xcodeproj/project.pbxproj
  Source/Collection/Animator/CollectionBatchUpdatesAnimator.swift
  Source/Collection/Collection+RDDM.swift
  Source/Collection/CollectionBuilder.swift
  Source/Collection/CollectionBuilderConfigurable.swift
  Source/Collection/DataSource/BaseCollectionDataSource.swift
  Source/Collection/DataSource/CollectionDataSource.swift
  Source/Collection/Delegate/BaseCollectionDelegate.swift
  Source/Collection/Delegate/CollectionDelegate.swift
  Source/Collection/Manager/BaseCollectionManager.swift
  Source/Collection/Plugins/PluginAction/CollectionPrefetcherablePlugin.swift
  Source/Collection/Protocols/CollectionItemTitleDisplayable.swift
  Source/Protocols/Animator/Animator.swift
  Source/Protocols/Modifier/Modifier.swift
  Source/Protocols/Plugins/FeaturePlugin/FeaturePlugin.swift
  Source/Protocols/Plugins/FeaturePlugin/TableFeaturePlugin/TableMovable.swift
  Source/Protocols/Plugins/Generators/ConfigurableItem.swift
  Source/Protocols/Plugins/Generators/DisplayableItem.swift
  Source/Protocols/Plugins/Generators/FoldableItem.swift
  Source/Protocols/Plugins/Generators/GravityItem.swift
  Source/Protocols/Plugins/Generators/IndexTitleDisplaybleItem.swift
  Source/Protocols/Plugins/Generators/MovableItem.swift
  Source/Protocols/Plugins/Generators/PrefetcherableItem.swift
  Source/Protocols/Plugins/Generators/SelectableItem.swift
  Source/Protocols/Plugins/Generators/SizableItem.swift
  Source/Protocols/Plugins/Generators/SwipeableItem.swift
  Source/Protocols/Plugins/PluginAction/Plugin.swift
  Source/Protocols/Plugins/PluginAction/PluginCollection.swift
  Source/Table/Animator/TableBatchUpdatesAnimator.swift
  Source/Table/Animator/TableUpdatesAnimator.swift
  Source/Table/DataSource/BaseTableDataSource.swift
  Source/Table/DataSource/DiffableTableDataSource.swift
  Source/Table/Delegate/BaseTableDelegate.swift
  Source/Table/Modifier/TableCommonModifier.swift
  Source/Table/Modifier/TableDiffableModifier.swift
  Source/Table/Plugins/FeaturePlugin/TableMovablePlugin.swift
  Source/Table/TableBuilderConfigurable.swift
Labels: Refactoring
