Repository surfstudio/ReactiveDataDisplayManager, pull requests merged in 2023-05, with the labels that each got.

#214 SPT-1455 Сделать Foldable plugin доступным для BaseManager
  Example/ReactiveDataDisplayManager/Table/FoldableTableViewController/FoldableTableViewController.swift
  Example/ReactiveDataDisplayManager/Table/Views/Cells/Generators/FoldableCellGenerator.swift
  Source/Protocols/Plugins/Generators/FoldableItem.swift
  Source/Table/Manager/BaseTableManager.swift
  Source/Table/Manager/ManualTableManager.swift
  Source/Table/Plugins/PluginAction/TableFoldablePlugin.swift
Labels: feature

#215 Feature/spt 1456/stress test
  Example/ReactiveDataDisplayManager/Collection/PaginatableCollectionViewController/PaginatableCollectionViewController.swift
  Example/ReactiveDataDisplayManager/Extensions/SampleError.swift
  Example/ReactiveDataDisplayManager/Extensions/UIButton.swift
  Example/ReactiveDataDisplayManager/Extensions/UILabel.swift
  Example/ReactiveDataDisplayManager/Table/AllPluginsTableViewController/AllPluginsTableViewController.swift
  Example/ReactiveDataDisplayManager/Table/FoldableTableViewController/FoldableTableViewController.swift
  Example/ReactiveDataDisplayManager/Table/PaginatableTableViewController/PaginatableTableViewController.swift
  Example/ReactiveDataDisplayManager/Table/Views/Cells/ExpandableTableCell/ExpandableTableCell.swift
  Example/ReactiveDataDisplayManager/Table/Views/Cells/Generators/FoldableCellGenerator.swift
  Example/ReactiveDataDisplayManager/Table/Views/PaginatorView.swift
  Example/ReactiveDataDisplayManager/Utils/UIViewController+Delay.swift
  Example/ReactiveDataDisplayManagerExampleUITests/BaseClasses/BaseUITestCase.swift
  Example/ReactiveDataDisplayManagerExampleUITests/Plugins/PaginatablePluginExampleUITest.swift
  Example/ReactiveDataDisplayManagerExampleUITests/Stress/AllPluginsStressTest.swift
  Example/targets/template.yml
  Gemfile.lock
  ReactiveDataDisplayManager.podspec
  ReactiveDataDisplayManagerTests/Builder/Collection/CollectionBuilderTests.swift
  ReactiveDataDisplayManagerTests/Builder/Collection/Stubs/CollectionAnimatorStub.swift
  ReactiveDataDisplayManagerTests/Builder/Table/Stubs/TableAnimatorStub.swift
  ReactiveDataDisplayManagerTests/Builder/Table/TableBuilderTests.swift
  Source/Collection/Animator/CollectionBatchUpdatesAnimator.swift
  Source/Collection/CollectionBuilder.swift
  Source/Collection/DataSource/BaseCollectionDataSource.swift
  Source/Collection/Plugins/PluginAction/CollectionPaginatablePlugin.swift
  Source/Common/QueuedAnimator.swift
  Source/Protocols/Animator/Animator.swift
  Source/Protocols/Plugins/FeaturePlugin/MovablePlugin/MovablePluginDataSource.swift
  Source/Protocols/Plugins/Generators/FoldableItem.swift
  Source/Table/DataSource/BaseTableDataSource.swift
  Source/Table/Manager/BaseTableManager.swift
  Source/Table/Manager/ManualTableManager.swift
  Source/Table/Plugins/PluginAction/TableFoldablePlugin.swift
  Source/Table/Plugins/PluginAction/TablePaginatablePlugin.swift
  Source/Table/TableBuilder.swift
  Source/Utils/Debouncer.swift
  project.yml
Labels: bug, enhancement

#218 SPT-1002 PoC of decoration
  Components/Sources/Collection/AnyIdentifiableCollectionGenerator.swift
  Components/Sources/Collection/DecorationProviders/CollectionDecorationProvider.swift
  Components/Sources/Common/Decorators/EachItemDecorator.swift
  Components/Sources/Common/Decorators/FirstItemDecorator.swift
  Components/Sources/Common/Decorators/LastItemDecorator.swift
  Components/Sources/Common/Decorators/NonEmptyDecorator.swift
  Components/Sources/Common/HashCombiners/CommonHashCombiner.swift
  Components/Sources/Common/Models/Decoration.swift
  Components/Sources/Common/Models/DecorationAnchor.swift
  Components/Sources/Common/Models/DecorationRule.swift
  Components/Sources/Common/Protocols/DecorationProvider.swift
  Components/Sources/Common/Protocols/Decorator.swift
  Components/Sources/Common/Protocols/HashCombiner.swift
  Components/Sources/Common/Utils/Decoration+Provider.swift
  Components/Sources/Common/Utils/DecorationRule+Decorator.swift
  Components/Sources/Common/Utils/Section+Decoration.swift
  Components/Sources/Common/Views/SpacerView.swift
  Components/Sources/Table/AnyIdentifiableTableGenerator.swift
  Components/Sources/Table/DecorationProviders/TableDecorationProvider.swift
  Example/ReactiveDataDisplayManager/Collection/DiffableCollectionViewController/DiffableCollectionViewController.swift
  Example/ReactiveDataDisplayManager/Table/DiffableTableViewController/DiffableTableViewController.swift
  Source/Table/DataSource/DiffableTableDataSource.swift
Labels: enhancement, feature

#219 SPT-1360 Создать текстовую ячейку
  Components/Sources/Collection/CollectionWrappedCell.swift
  Components/Sources/Common/Views/LabelView.swift
  Components/Sources/Table/TableWrappedCell.swift
  Example/ReactiveDataDisplayManager/Table.storyboard
  Example/ReactiveDataDisplayManager/Table/ComponentsOverviewTableViewController/ComponentsOverviewTableViewController.swift
  Example/ReactiveDataDisplayManager/Table/MainTableViewController/MainTableViewController.swift
Labels: feature

#221 SPT-1362 Создать ячейку сообщения
  Components/Sources/Common/Protocols/AlignmentProvider.swift
  Components/Sources/Common/Utils/UIView+Constraints.swift
  Components/Sources/Common/Utils/ViewWrapper.swift
  Components/Sources/Common/Views/LabelView.swift
  Components/Sources/Common/Views/MessageView.swift
  Example/ReactiveDataDisplayManager/Table/ComponentsOverviewTableViewController/ComponentsOverviewTableViewController.swift
Labels: feature, Blocker
