Repository surfstudio/ReactiveDataDisplayManager, pull requests merged in 2023-07, with the labels that each got.

#237 [SPT-1363] Таблица - плагин TwoDirectionalPaginatable
  Example/ReactiveDataDisplayManager/Extensions/UIBarButtonItem.swift
  Example/ReactiveDataDisplayManager/Extensions/UIButton.swift
  Example/ReactiveDataDisplayManager/Extensions/UILabel.swift
  Example/ReactiveDataDisplayManager/Table.storyboard
  Example/ReactiveDataDisplayManager/Table/MainTableViewController/MainTableViewController.swift
  Example/ReactiveDataDisplayManager/Table/TwoDirectionPaginatableTableViewController/TwoDirectionPaginatableTableViewController.swift
  Example/ReactiveDataDisplayManagerExampleUITests/Plugins/TwoDirectionPaginatableExampleUITest.swift
  Source/Table/Manager/BaseTableManager.swift
  Source/Table/Manager/ManualTableManager.swift
  Source/Table/Plugins/PluginAction/TableBackwardPaginatablePlugin.swift
  Source/Table/Plugins/PluginAction/TablePaginatablePlugin.swift
Labels: question, feature, 8.0

#241 [SPT-1364] [Коллекция] Плагин TwoDirectionalPaginatable
  Example/ReactiveDataDisplayManager/Collection.storyboard
  Example/ReactiveDataDisplayManager/Collection/MainCollectionViewController/MainCollectionViewController.swift
  Example/ReactiveDataDisplayManager/Collection/TwoDirectionPaginatableCollectionViewController/TwoDirectionPaginatableCollectionViewController.swift
  Example/ReactiveDataDisplayManager/Collection/Views/Cells/TitleCollectionViewCell/TitleCollectionViewCell.swift
  Source/Collection/Manager/BaseCollectionManager.swift
  Source/Collection/Plugins/PluginAction/CollectionBackwardPaginatablePlugin.swift
  Source/Collection/Plugins/PluginAction/CollectionPaginatablePlugin.swift
Labels: feature, 8.0

#246 Hotfix/spt 1546/insert func optimisation
  Example/ReactiveDataDisplayManager/Table/AllPluginsTableViewController/AllPluginsTableViewController.swift
  ReactiveDataDisplayManagerTests/Mocks/AutoMockable.generated.swift
  Source/Collection/Manager/BaseCollectionManager.swift
  Source/Collection/Modifier/CollectionCommonModifier.swift
  Source/Collection/Modifier/CollectionDiffableModifier.swift
  Source/Protocols/Modifier/Modifier.swift
  Source/Table/Manager/BaseTableManager.swift
  Source/Table/Manager/ManualTableManager.swift
  Source/Table/Modifier/TableCommonModifier.swift
  Source/Table/Modifier/TableDiffableModifier.swift
Labels: bug, 7.3.7

#243 [SPT-1514] Попробовать затянуть подскролл прямо в плагин backward paginatable
  Example/ReactiveDataDisplayManager/Collection/TwoDirectionPaginatableCollectionViewController/TwoDirectionPaginatableCollectionViewController.swift
  Example/ReactiveDataDisplayManager/Table/TwoDirectionPaginatableTableViewController/TwoDirectionPaginatableTableViewController.swift
  Example/ReactiveDataDisplayManagerExampleUITests/Plugins/TwoDirectionPaginatableExampleUITest.swift
  Source/Collection/Plugins/PluginAction/CollectionPaginatablePlugin.swift
  Source/Collection/Plugins/PluginAction/CollectionTopPaginatablePlugin.swift
  Source/Table/Plugins/PluginAction/TablePaginatablePlugin.swift
  Source/Table/Plugins/PluginAction/TableTopPaginatablePlugin.swift
Labels: question, feature, 8.0

#245 [SPT-1522] Добавление стек-генераторов
  Components/Sources/Collection/CollectionStack/CollectionStack.swift
  Components/Sources/Collection/CollectionStack/HorizontalCollectionStack.swift
  Components/Sources/Collection/CollectionStack/StackCollectionCell.swift
  Components/Sources/Collection/CollectionStack/VerticalCollectionStack.swift
  Components/Sources/Common/Extensions/BaseCollectionManager+Extension.swift
  Components/Sources/Common/Extensions/CollectionWrappedCell+RDDM.swift
  Components/Sources/Common/Extensions/ConfigurableItem+Builder.swift
  Components/Sources/Common/Extensions/UIStackView+Extension.swift
  Components/Sources/Common/Extensions/UIView+Extension.swift
  Components/Sources/Table/TableStack/HorizontalTableStack.swift
  Components/Sources/Table/TableStack/StackTableCell.swift
  Components/Sources/Table/TableStack/TableStack.swift
  Components/Sources/Table/TableStack/VerticalTableStack.swift
  Example/ReactiveDataDisplayManager/Collection.storyboard
  Example/ReactiveDataDisplayManager/Collection/MainCollectionViewController/MainCollectionViewController.swift
  Example/ReactiveDataDisplayManager/Collection/StackCellExampleCollectionViewController/StackCellExampleCollectionViewController.swift
  Example/ReactiveDataDisplayManager/Collection/Views/Cells/HighlitableStackCells/StackCollectionCell+HighlitableItem.swift
  Example/ReactiveDataDisplayManager/Table.storyboard
  Example/ReactiveDataDisplayManager/Table/MainTableViewController/MainTableViewController.swift
  Example/ReactiveDataDisplayManager/Table/StackCellExampleViewController/StackCellExampleViewController.swift
  Example/ReactiveDataDisplayManager/Table/Views/Cells/HighlitableStackCells/StackTableCell+HighlitableItem.swift
  Example/ReactiveDataDisplayManager/Table/Views/Cells/TitleTableViewCell/TitleTableViewCell.swift
  Source/Models/Section.swift
  Source/Table/Plugins/PluginAction/TableHighlightPlugin.swift
Labels: feature, 8.0

#247 [SPT-471] Решить проблему нерабочих плагинов в compositionalLayout
  .github/workflows/Build.yml
  Example/ReactiveDataDisplayManager/Collection/CollectionCompositionalViewController/CollectionCompositionalViewController.swift
  Source/Collection/Plugins/PluginAction/CollectionScrollViewDelegateProxyPlugin.swift
  Source/Collection/Plugins/PluginAction/CollectionScrollablePlugin.swift
Labels: bug, 8.0

#250 Fix codecov uploader failures
  .github/workflows/Build.yml
Labels: bug, 8.0

#252 Bugfix/spt 1564/register at insert
  Example/targets/template.yml
  ReactiveDataDisplayManager.podspec
  Source/Collection/Manager/BaseCollectionManager.swift
  Source/Table/Manager/BaseTableManager.swift
  Source/Table/Manager/ManualTableManager.swift
  project.yml
Labels: bug, 7.3.8

#244 [SPT-1478] Интерактивность MessageView
  Components/Sources/Common/Models/Styles/DataDetectionStyle.swift
  Components/Sources/Common/Utils/ViewWrapper.swift
  Components/Sources/Common/Views/MessageView.swift
  Example/ReactiveDataDisplayManager/Table/ComponentsOverviewTableViewController/ComponentsOverviewTableViewController.swift
Labels: question, feature, 8.0

#249 SPT-1521 RDDM. Унифицировать BaseEvent
  Components/Sources/Collection/CollectionStack/CollectionStack.swift
  Components/Sources/Collection/CollectionStack/StackCollectionCell.swift
  Components/Sources/Table/TableStack/StackTableCell.swift
  Components/Sources/Table/TableStack/TableStack.swift
  Example/ReactiveDataDisplayManager/Collection/Views/Cells/Generators/SwipeableCollectionGenerator.swift
  Example/ReactiveDataDisplayManager/Table/Views/Cells/ExpandableTableCell/ExpandableTableCell.swift
  Example/ReactiveDataDisplayManager/Table/Views/Cells/Generators/SwipeableTableGenerator.swift
  Example/ReactiveDataDisplayManager/Table/Views/Headers/Generators/SectionTitleHeaderGenerator.swift
  ReactiveDataDisplayManagerTests/Mocks/AutoMockable.generated.swift
  ReactiveDataDisplayManagerTests/Table/Manager/GravityFoldingHeaderGenerator.swift
  ReactiveDataDisplayManagerTests/Utils/BaseEventTests.swift
  Source/Collection/Generators/BaseCollectionCellGenerator.swift
  Source/Collection/Generators/FoldableCollectionCellGenerator.swift
  Source/Collection/Plugins/PluginAction/BaseCollectionPlugin.swift
  Source/Collection/Plugins/PluginAction/CollectionPrefetchProxyPlugin.swift
  Source/Collection/Plugins/PluginAction/CollectionScrollViewDelegateProxyPlugin.swift
  Source/Collection/Plugins/PluginAction/CollectionSelectablePlugin.swift
  Source/Collection/Protocols/CollectionFoldableItem.swift
  Source/Protocols/Plugins/Generators/DeletableItem.swift
  Source/Protocols/Plugins/Generators/DisplayableItem.swift
  Source/Protocols/Plugins/Generators/ExpandableItem.swift
  Source/Protocols/Plugins/Generators/FoldableItem.swift
  Source/Protocols/Plugins/Generators/SelectableItem.swift
  Source/Protocols/Plugins/Generators/SwipeableItem.swift
  Source/Protocols/Plugins/PluginAction/Plugin.swift
  Source/Protocols/Plugins/PluginAction/PluginCollection.swift
  Source/Table/Generators/BaseCellGenerator.swift
  Source/Table/Generators/BaseNonReusableCellGenerator.swift
  Source/Table/Generators/CalculatableHeightNonReusableCellGenerator.swift
  Source/Table/Generators/FoldableCellGenerator.swift
  Source/Table/Plugins/PluginAction/BaseTablePlugin.swift
  Source/Table/Plugins/PluginAction/TableDisplayablePlugin.swift
  Source/Table/Plugins/PluginAction/TablePrefetchProxyPlugin.swift
  Source/Table/Plugins/PluginAction/TableScrollViewDelegateProxyPlugin.swift
  Source/Table/Plugins/PluginAction/TableSelectablePlugin.swift
  Source/Utils/Event.swift
Labels: enhancement, 8.0

#251 SPT-1554 Сделать SpacerView горизонтальным
  Components/Sources/Common/Models/ViewSize.swift
  Components/Sources/Common/Views/SeparatorView.swift
  Components/Sources/Common/Views/SpacerView.swift
  Example/ReactiveDataDisplayManager/Collection/StackCellExampleCollectionViewController/StackCellExampleCollectionViewController.swift
  Example/ReactiveDataDisplayManager/Collection/TwoDirectionPaginatableCollectionViewController/TwoDirectionPaginatableCollectionViewController.swift
  Example/ReactiveDataDisplayManager/Table/ComponentsOverviewTableViewController/ComponentsOverviewTableViewController.swift
  Example/ReactiveDataDisplayManager/Table/DiffableTableViewController/DiffableTableViewController.swift
Labels: feature, 8.0

#248 SPT-1477 Добавление SizableItem компонентам
  Components/Sources/Collection/CollectionWrappedCell.swift
  Components/Sources/Common/Extensions/CollectionWrappedCell+RDDM.swift
  Components/Sources/Common/Models/ViewSize.swift
  Components/Sources/Common/Protocols/FrameProvider.swift
  Components/Sources/Common/Protocols/TextProvider.swift
  Components/Sources/Common/Views/LabelView.swift
  Components/Sources/Common/Views/MessageView.swift
  Components/Sources/Common/Views/SeparatorView.swift
  Components/Sources/Common/Views/SpacerView.swift
  Components/Sources/Table/TableWrappedCell+RDDM.swift
  Components/Sources/Table/TableWrappedCell.swift
Labels: feature, 8.0
